// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EvxVuSLS1M_jlskOZ9J6m4W-fR8iCa4',
    appId: '1:879448455612:web:7496ce70a9d873eb5bd3b9',
    messagingSenderId: '879448455612',
    projectId: 'shoesapp-bfbea',
    authDomain: 'shoesapp-bfbea.firebaseapp.com',
    storageBucket: 'shoesapp-bfbea.firebasestorage.app',
    measurementId: 'G-K1ZRF87KNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFM9GGr-M0IH-trNeKVej-lwbyp8CB8lo',
    appId: '1:879448455612:android:a168f481d1cd75ad5bd3b9',
    messagingSenderId: '879448455612',
    projectId: 'shoesapp-bfbea',
    storageBucket: 'shoesapp-bfbea.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4EvxVuSLS1M_jlskOZ9J6m4W-fR8iCa4',
    appId: '1:879448455612:web:97521564d74974a55bd3b9',
    messagingSenderId: '879448455612',
    projectId: 'shoesapp-bfbea',
    authDomain: 'shoesapp-bfbea.firebaseapp.com',
    storageBucket: 'shoesapp-bfbea.firebasestorage.app',
    measurementId: 'G-2VYFN3MRWC',
  );
}
